### ISSUE TITLE
Помогите запустить бота, чтоб все работало  

### ISSUE THREAD

**Issue by triplesss1** [iholston/lol-bot#127]
[16:15:28] [INFO   ] Overwriting/creating game config
[16:15:28] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'
[16:15:28] [ERROR  ] Traceback (most recent call last):
  File "C:\Users\User\Desktop\Питончик\lol-bot-2.0.0\app\bot\client.py", line 54, in account_loop
    self.launcher.launch_league(account.get_username(), account.get_password())
  File "C:\Users\User\Desktop\Питончик\lol-bot-2.0.0\app\bot\launcher.py", line 33, in launch_league
    self.set_game_config()
  File "C:\Users\User\Desktop\Питончик\lol-bot-2.0.0\app\bot\launcher.py", line 42, in set_game_config
    shutil.copyfile(LOCAL_GAME_CONFIG_PATH, LEAGUE_GAME_CONFIG_PATH)
  File "C:\Program Files\Python312\Lib\shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'

[16:15:28] [ERROR  ] Bot Exiting

**Comment by iholston** [comment]
Bot cannot override the game.cfg file. which version of the bot are you using?

**Comment by triplesss1** [comment]
2.0.0

**Comment by iholston** [comment]
Yea its hard to tell how to solve this issue. I recommend downgrading to v1.3.2 and running the launcher.py file as administrator. I will try to address this issue in 2.0.1.

**Comment by triplesss1** [comment]
How to downgrade to 1.3.2?

**Comment by iholston** [comment]
Go [here](https://github.com/iholston/lol-bot/releases) and download 1.3.2

**Comment by iholston** [comment]
I would just unzip it to your desktop

**Comment by triplesss1** [comment]
![2023-11-08_21-14-46](https://github.com/iholston/lol-bot/assets/150136869/d6cdd917-b2b5-4457-9f45-7cec576a1cba)


[08 Nov 2023 21:13:48] [INFO   ] [set_game_config      ] Overwriting/creating game config
[08 Nov 2023 21:13:48] [ERROR  ] [account_loop         ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\lol-bot\lol-bot-1.3.2\scripts\client.py", line 49, in account_loop
    self.launcher.launch_league(account.get_username(), account.get_password())
  File "C:\Users\User\Desktop\lol-bot\lol-bot-1.3.2\scripts\launcher.py", line 34, in launch_league
    self.set_game_config()
  File "C:\Users\User\Desktop\lol-bot\lol-bot-1.3.2\scripts\launcher.py", line 43, in set_game_config
    shutil.copyfile(LOCAL_GAME_CONFIG_PATH, LEAGUE_GAME_CONFIG_PATH)
  File "C:\Program Files\Python312\Lib\shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'
[08 Nov 2023 21:13:48] [ERROR  ] [account_loop         ] None

C:\Users\User\Desktop\lol-bot\lol-bot-1.3.2\scripts>pause
Для продолжения нажмите любую клавишу . . .

**Comment by iholston** [comment]
this is when you ran it as administrator?

**Comment by triplesss1** [comment]
yeah

**Comment by iholston** [comment]
Alright well, I don't know what the issue could be exactly. For some reason you cannot modify the game.cfg in Riot Games/League of Legends/Config

**Comment by iholston** [comment]
in the meantime you can comment out the line with the copyfile in launcher.py, but you will have to copy the game.cfg from resources to the league folder

**Comment by triplesss1** [comment]
thank you very much, I am very glad that you answered. everything works <3
