### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Emilsagefalk** [iholston/lol-bot#157]
This is my first time using this bot and when trying to use it I get this error. How do I resolve this? 

[16:28:26] [INFO   ] Overwriting/creating game config
[16:28:26] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'
[16:28:26] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 66, in account_loop
  File "lolbot\bot\launcher.py", line 37, in launch_league
  File "lolbot\bot\launcher.py", line 48, in set_game_config
  File "shutil.py", line 423, in copy
  File "shutil.py", line 262, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'

[16:28:26] [ERROR  ] Unknown Error. Exiting

https://imgur.com/a/pozorfC

**Comment by Emilsagefalk** [comment]
Found another user with the sameproblem. The config file was set to read only. My fault.
