### ISSUE TITLE
Can not change account after first account reach lv10?

### ISSUE THREAD

**Issue by ericshug** [iholston/lol-bot#162]
**Describe the bug**

**Version**
v2.2.0

**Screenshots**
![33](https://github.com/iholston/lol-bot/assets/11578730/1b1da396-51d0-4844-b872-1302e5d761ca)
![35](https://github.com/iholston/lol-bot/assets/11578730/30467355-ab40-4251-b04b-32426b6482c5)

**Log Files**
[07:47:13] [INFO   ] SUCCESS: Account Leveled
[07:47:13] [INFO   ] Terminating league related processes
[07:47:18] [INFO   ] Overwriting/creating game config
[07:47:18] [WARNING] No account set. Add accounts on account page
[07:47:19] [WARNING] League opened with prior login
[07:47:19] [INFO   ] Verifying logged-in account credentials
[07:47:22] [WARNING] Incorrect Account! Proceeding anyways
[07:47:26] [INFO   ] Checking for Client Updates
[07:47:26] [INFO   ] Client is up to date
[07:47:27] [ERROR  ] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[07:47:27] [ERROR  ] Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 461, in getresponse
  File "http\client.py", line 1411, in getresponse
  File "http\client.py", line 324, in begin
  File "http\client.py", line 293, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 470, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 461, in getresponse
  File "http\client.py", line 1411, in getresponse
  File "http\client.py", line 324, in begin
  File "http\client.py", line 293, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lolbot\bot\client.py", line 67, in account_loop
  File "lolbot\bot\client.py", line 96, in leveling_loop
  File "lolbot\bot\client.py", line 306, in account_leveled
  File "lolbot\common\api.py", line 144, in request
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

[07:47:27] [ERROR  ] Unknown Error. Exiting
**Additional context**

**Comment by ericshug** [comment]
[04122023_1425.log](https://github.com/iholston/lol-bot/files/13553826/04122023_1425.log)

**Comment by iholston** [comment]
where is league of legends installed? this error seems odd, because if league is running there should always be a lockfile. Is your league of legends installed in C:/Riot Games/League of Legends  on your win 10 pc?

**Comment by ericshug** [comment]
[05122023_1032.log](https://github.com/iholston/lol-bot/files/13554270/05122023_1032.log)
Yes,C:\Riot Games\League of Legends.

**Comment by iholston** [comment]
Okay, i think this is a bug. Check your accounts tab and see if the 'level' actually matches up with the real level of the account. This if not, then reset the levels to 1 and close the league client and restart and it should work properly. This will be fixed in the next version (2.2.1)

**Comment by ericshug** [comment]
add my DC id: xbabytank, I stream my game.

**Comment by ericshug** [comment]
And it can't select new account 7 day champion reward when leve up.

**Comment by ericshug** [comment]
Bot tab,restart UX work,close client not work.

**Comment by iholston** [comment]
This should be fixed in the latest bot version 2.3.0
