### ISSUE TITLE
Can this robot be used in China?How to set up account?

### ISSUE THREAD

**Issue by Z2zzz** [iholston/lol-bot#163]
**Describe the bug**
This program doesn't work on my computer,I'm not sure how this account is set up
**Version**
What version of the lol-bot are you running?
2.2.0
**Screenshots**
![Snipaste_2023-12-05_20-48-48](https://github.com/iholston/lol-bot/assets/87265260/bb26f2f6-df3b-441b-8049-f2982bdeba2c)
![Snipaste_2023-12-05_20-48-481](https://github.com/iholston/lol-bot/assets/87265260/f171fdf4-5ebe-40fa-b88c-01da516ceab3)
![Snipaste_2023-12-05_20-50-19](https://github.com/iholston/lol-bot/assets/87265260/5c7415af-6b42-466d-a4cb-409aa2ce05e5)

**Log Files**
If applicable, add the log file containing the error messages from your issue
[20:51:14] [WARNING] League opened with prior login
[20:51:14] [INFO   ] Verifying logged-in account credentials
[20:51:15] [ERROR  ] 'state'
[20:51:15] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 68, in account_loop
  File "lolbot\bot\launcher.py", line 38, in launch_league
  File "lolbot\bot\launcher.py", line 54, in launch_loop
  File "lolbot\bot\launcher.py", line 110, in verify_account
  File "lolbot\common\api.py", line 116, in connect_lcu
KeyError: 'state'

[20:51:15] [ERROR  ] Unknown Error. Exiting
**Additional context**

**Comment by iholston** [comment]
I'm not sure if it works in China, I'll look into this though

**Comment by Z2zzz** [comment]
Thank you very much, I am looking forward to this robot can also be applied in China.
