### ISSUE TITLE
it gives me an error

### ISSUE THREAD

**Issue by haxerman1** [iholston/lol-bot#173]
it gives me an error and it doesnt work

[17:18:45] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'
[17:18:45] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 69, in account_loop
  File "lolbot\bot\client.py", line 103, in leveling_loop
  File "lolbot\bot\client.py", line 389, in set_game_config
  File "shutil.py", line 423, in copy
  File "shutil.py", line 262, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'

pls help me fix it as i want to use this bot

edit: ive found the problem and it is that it has two slashes in c:/riotgame/lol and before lol and after config theres twoo slashes and i dont know how to fix it

another edit: ive fixed that but it still gives me an error
[17:51:44] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'
[17:51:44] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 69, in account_loop
  File "lolbot\bot\client.py", line 99, in leveling_loop
  File "lolbot\bot\client.py", line 385, in set_game_config
  File "shutil.py", line 423, in copy
  File "shutil.py", line 262, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends/Config/game.cfg'

[17:51:44] [ERROR  ] Unknown Error. Exiting

ANOTHER EDIT: ive fixed it

**Comment by SageKatalyst** [comment]
how to fix it?
