### ISSUE TITLE
config file permission error

### ISSUE THREAD

**Issue by sirdali00** [iholston/lol-bot#197]
can someone hellp me to fix this error

[ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'
[01:09:50] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 69, in account_loop
  File "lolbot\bot\client.py", line 103, in leveling_loop
  File "lolbot\bot\client.py", line 389, in set_game_config
  File "shutil.py", line 423, in copy
  File "shutil.py", line 262, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'

**Comment by iholston** [comment]
try running the bot as administrator

**Comment by sirdali00** [comment]
i did that but still bot is showing me that error

**Comment by sirdali00** [comment]
![Uploading 3.png…]()

**Comment by sirdali00** [comment]
![3](https://github.com/iholston/lol-bot/assets/154507955/365b0327-3972-4a3b-81e1-0d4552d4257e)

**Comment by iholston** [comment]
try deleting that file. C:\riot games\league of legends\config\game.cfg and then running the bot
