### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by abubaker1771b** [iholston/lol-bot#220]
[02:40:03] [WARNING] No account set. Add accounts on account page
[02:40:04] [WARNING] League opened with prior login
[02:40:04] [INFO   ] Verifying logged-in account credentials
[02:40:07] [WARNING] Accounts do not match! Proceeding anyways
[02:40:11] [INFO   ] Checking for Client Updates
[02:40:11] [INFO   ] Client is up to date
[02:40:11] [INFO   ] Overwriting game configs
[02:40:11] [ERROR  ] [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'
[02:40:11] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 69, in account_loop
    self.leveling_loop()
  File "lolbot\bot\client.py", line 103, in leveling_loop
    self.set_game_config()
  File "lolbot\bot\client.py", line 389, in set_game_config
    shutil.copy(utils.resource_path(Constants.GAME_CFG), path)
  File "shutil.py", line 435, in copy
  File "shutil.py", line 262, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:/Riot Games/League of Legends\\Config/game.cfg'

[02:40:11] [ERROR  ] Unknown Error. Exiting

**Comment by iholston** [comment]
you have permissions set to read only on game.cfg. or you need to run the bot as admin
