### ISSUE TITLE
LOL BOT is not working when game ends

### ISSUE THREAD

**Issue by Piedamante** [iholston/lol-bot#230]
when the game ends it doesnt search for a new game it requires a manuel help to actually work again it says: [01 Aug 2024 21:47:29] [ERROR  ] [account_loop         ] Unknown Error. Exiting...

**Comment by igotario** [comment]
same

**Comment by luniiix** [comment]
Had the error too, it's for the honoring teammates.
[20:42:38] [INFO   ] Honoring teammates and accepting rewards
[20:42:44] [ERROR  ] 'eligiblePlayers'
[20:42:44] [ERROR  ] Traceback (most recent call last):
  File "lolbot\bot\client.py", line 69, in account_loop
  File "lolbot\bot\client.py", line 129, in leveling_loop
  File "lolbot\bot\client.py", line 288, in pre_end_of_game
  File "lolbot\bot\client.py", line 346, in honor_player
KeyError: 'eligiblePlayers'

[20:42:44] [ERROR  ] Unknown Error. Exiting

**Comment by Piedamante** [comment]
btw dont use the bot. i got banned

**Comment by luniiix** [comment]
me too ! Be care all

**Comment by mr-nobrain** [comment]
Fix the loop for starting new game, or anyone know how to fix the issue?

**Comment by iholston** [comment]
Should be fixed with the latest release.
