### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by viasbox** [iholston/lol-bot#250]
**Describe the bug**
The client starts, but but doesn't look for a game, since it can't find the config. If I put a config file into the config folder it also gets deleted once I run the bot through python.

**Version**
2.3.1

**Log Files**
[16 Oct 2024 15:37:10] [WARNING] [launch_loop          ] League opened with prior login
[16 Oct 2024 15:37:10] [INFO   ] [verify_account       ] Verifying logged-in account credentials
[16 Oct 2024 15:37:10] [DEBUG  ] [connect_lcu          ] Connecting to LCU API
[16 Oct 2024 15:37:10] [DEBUG  ] [connect_lcu          ] LeagueClient:10992:3582:dW68U8TY3jhjDrNKDFRgmQ:https
[16 Oct 2024 15:37:10] [DEBUG  ] [connect_lcu          ] Basic cmlvdDpkVzY4VThUWTNqaGpEck5LREZSZ21R
[16 Oct 2024 15:37:11] [DEBUG  ] [request              ] GET https://127.0.0.1:3582/lol-login/v1/session {}
[16 Oct 2024 15:37:11] [DEBUG  ] [connect_lcu          ] Connection Successful
[16 Oct 2024 15:37:11] [DEBUG  ] [request              ] POST https://127.0.0.1:3582/lol-login/v1/delete-rso-on-close {}
[16 Oct 2024 15:37:13] [DEBUG  ] [request              ] GET https://127.0.0.1:3582/lol-login/v1/session {}
[16 Oct 2024 15:37:13] [INFO   ] [verify_account       ] Account Verified
[16 Oct 2024 15:37:13] [DEBUG  ] [connect_lcu          ] Connecting to LCU API
[16 Oct 2024 15:37:13] [DEBUG  ] [connect_lcu          ] LeagueClient:10992:3582:dW68U8TY3jhjDrNKDFRgmQ:https
[16 Oct 2024 15:37:13] [DEBUG  ] [connect_lcu          ] Basic cmlvdDpkVzY4VThUWTNqaGpEck5LREZSZ21R
[16 Oct 2024 15:37:14] [DEBUG  ] [request              ] GET https://127.0.0.1:3582/lol-login/v1/session {}
[16 Oct 2024 15:37:14] [DEBUG  ] [connect_lcu          ] Connection Successful
[16 Oct 2024 15:37:14] [DEBUG  ] [request              ] POST https://127.0.0.1:3582/lol-login/v1/delete-rso-on-close {}
[16 Oct 2024 15:37:16] [DEBUG  ] [request              ] GET https://127.0.0.1:3582/lol-gameflow/v1/gameflow-phase {}
[16 Oct 2024 15:37:16] [DEBUG  ] [get_phase            ] New Phase: None, Previous Phase: 
[16 Oct 2024 15:37:18] [INFO   ] [check_patch          ] Checking for Client Updates
[16 Oct 2024 15:37:18] [DEBUG  ] [request              ] GET https://127.0.0.1:3582/patcher/v1/products/league_of_legends/state {}
[16 Oct 2024 15:37:18] [INFO   ] [check_patch          ] Client is up to date
[16 Oct 2024 15:37:18] [INFO   ] [set_game_config      ] Overwriting game configs
[16 Oct 2024 15:37:18] [ERROR  ] [account_loop         ] [Errno 2] No such file or directory: 'C:\\WINDOWS\\System32\\lolbot/resources/game.cfg'
[16 Oct 2024 15:37:18] [ERROR  ] [account_loop         ] Traceback (most recent call last):
  File "D:\lol\test2\lol-bot-2.3.1\lolbot\bot\client.py", line 69, in account_loop
    self.leveling_loop()
  File "D:\lol\test2\lol-bot-2.3.1\lolbot\bot\client.py", line 103, in leveling_loop
    self.set_game_config()
  File "D:\lol\test2\lol-bot-2.3.1\lolbot\bot\client.py", line 389, in set_game_config
    shutil.copy(utils.resource_path(Constants.GAME_CFG), path)
  File "C:\Users\I\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 423, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\I\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\WINDOWS\\System32\\lolbot/resources/game.cfg'

**Additional context**
I started the main.py through python as admin and league is in the standard directory.
Also just used a lol cleaner beforehand if that matters.

**Comment by viasbox** [comment]
fixed by creating a lol bot folder & game.cfg file in the system 32 directory
