### ISSUE TITLE
中国版本是不是不支持请问

### ISSUE THREAD

**Issue by xunyangjian1** [iholston/lol-bot#269]
E:\TEST\lol-bot-4.0.0>python main.pyw
Traceback (most recent call last):
  File "E:\TEST\lol-bot-4.0.0\main.pyw", line 5, in <module>
    from lolbot.view.main_window import MainWindow
  File "E:\TEST\lol-bot-4.0.0\lolbot\view\main_window.py", line 9, in <module>
    from lolbot.view.bot_tab import BotTab
  File "E:\TEST\lol-bot-4.0.0\lolbot\view\bot_tab.py", line 14, in <module>
    from lolbot.common import config
  File "E:\TEST\lol-bot-4.0.0\lolbot\common\config.py", line 9, in <module>
    from lolbot.system import OS
  File "E:\TEST\lol-bot-4.0.0\lolbot\system\__init__.py", line 8, in <module>
    from .windows import mouse, keys, window, cmd
  File "E:\TEST\lol-bot-4.0.0\lolbot\system\windows\window.py", line 5, in <module>
    from win32gui import FindWindow, GetWindowRect
ModuleNotFoundError: No module named 'win32gui'

**Comment by iholston** [comment]
This should be fixed in the latest release 4.0.1
