### ISSUE TITLE
Unexpected Error: Traceback

### ISSUE THREAD

**Issue by kaorumitoma** [iholston/lol-bot#27]
This error occurred many times and i disconnected because of AFK.
This is copy from log file.please help me.

[23 Jun 2023 05:31:08] [WARNING] [main                 ] Unexpected Error: Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\lol-bot-main (5)\lol-bot-main\scripts\bot.py", line 40, in main
    client.loop()
  File "C:\Users\Administrator\Downloads\lol-bot-main (5)\lol-bot-main\scripts\client.py", line 76, in loop
    game.play_game()
  File "C:\Users\Administrator\Downloads\lol-bot-main (5)\lol-bot-main\scripts\game.py", line 47, in play_game
    utils.click(GAME_CENTER_OF_SCREEN, LEAGUE_GAME_CLIENT_WINNAME)
  File "C:\Users\Administrator\Downloads\lol-bot-main (5)\lol-bot-main\scripts\utils.py", line 57, in click
    pyautogui.moveTo(updated_x, updated_y)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 597, in wrapper
    failSafeCheck()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

**Comment by iholston** [comment]
Drop the whole log file and I'll look into it

**Comment by kaorumitoma** [comment]
[logs.txt](https://github.com/iholston/lol-bot/files/11849562/logs.txt)

**Comment by iholston** [comment]
I think I know what this issue is from looking at this, will try and have a fix out this weekend

**Comment by icyrs** [comment]
having the same issue with the failsafe

**Comment by iholston** [comment]
Should be good to go now
