### ISSUE TITLE
starting error

### ISSUE THREAD

**Issue by viasbox** [iholston/lol-bot#43]
Hello, I get an error when trying to start the bot. I made sure to have all the requirements from the txt file and added my normal python folder along with the scripts & libs folder to the system variables path. Also updated my install path, so I'm not sure what's wrong.
This is the error message:

[2023-07-29 02:32:13,532] [INFO   ] [launch_league        ] Overwriting/creating game config
[2023-07-29 02:32:13,534] [WARNING] [main                 ] Unexpected Error: Traceback (most recent call last):
  File "C:\Users\x\lol-bot\scripts\bot.py", line 38, in main
    launcher.launch_league()
  File "C:\Users\x\lol-bot\scripts\launcher.py", line 27, in launch_league
    shutil.copy2(LOCAL_GAME_CONFIG_PATH, LEAGUE_GAME_CONFIG_PATH)
  File "C:\Program Files\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python311\Lib\shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'D:\x0colders\\Riot Games\\League of Legends/Config/game.cfg'

C:\Users\x\lol-bot\scripts>pause

**Comment by iholston** [comment]
i believe you should change

> D:\x0colders\Riot Games\League of Legends/Config/game.cfg

to 

>  D:/x0colders/Riot Games/League of Legends/Config/game.cfg

**Comment by viasbox** [comment]
that was it, thank you!
