### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kunai12** [iholston/lol-bot#47]
When i open launcher i get this error:
C:\Users\PC\Desktop\lol-bot-main\scripts>python bot.py
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\lol-bot-main\scripts\bot.py", line 6, in <module>
    import launcher
  File "C:\Users\PC\Desktop\lol-bot-main\scripts\launcher.py", line 10, in <module>
    import utils
  File "C:\Users\PC\Desktop\lol-bot-main\scripts\utils.py", line 1, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

C:\Users\PC\Desktop\lol-bot-main\scripts>pause

**Comment by iholston** [comment]
I'm assuming you figured this out? If not, just make sure you run the requirements.txt file and that you don't have multiple versions/installations of python.
