### ISSUE TITLE
logger filepath issue

### ISSUE THREAD

**Issue by xvkyyy** [iholston/lol-bot#75]
C:\Users\Desktop\lol-bot-main\scripts>python bot.py
Traceback (most recent call last):
  File "C:\Users\\Desktop\lol-bot-main\scripts\bot.py", line 6, in <module>
    import launcher
  File "C:\Users\\Desktop\lol-bot-main\scripts\launcher.py", line 2, in <module>
    import api
  File "C:\Users\\Desktop\lol-bot-main\scripts\api.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

idk what i should do now

**Comment by xvkyyy** [comment]
Okey i fix that problem but now i have other XD
  File "C:\Users\Oskar\Desktop\lol-bot-1.1.2\scripts\bot.py", line 71, in <module>
    main()
  File "C:\Users\Oskar\Desktop\lol-bot-1.1.2\scripts\bot.py", line 22, in main
    fh = RotatingFileHandler(filename=filename, maxBytes=500000, backupCount=1)
  File "C:\Users\Oskar\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "C:\Users\Oskar\AppData\Local\Programs\Python\Python310\lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "C:\Users\Oskar\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1167, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Oskar\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1197, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Oskar\\Desktop\\lol-bot-1.1.2\\logs\\20092023_1735_log.log'

i tried #19 method but it dont work , i have log.txt on desktop , even try to command out in 14 in bot.py but still dont work

**Comment by iholston** [comment]
I see the issue, il be able to fix it tonight.

**Comment by iholston** [comment]
In the meantime, just create a folder called logs in folder containing the scripts folder and it should work

**Comment by iholston** [comment]
In the meantime, just create a folder called logs in folder containing the scripts folder and it should work

**Comment by iholston** [comment]
should be good now.

**Comment by xvkyyy** [comment]
> should be good now.
i fixed it using openai , and doing some things myself , but ye it was filepath issue
