### ISSUE TITLE
file not found, waht is happening ? 

### ISSUE THREAD

**Issue by Slavfucious** [iholston/lol-bot#99]
PS C:\Users\Slavfucious\Desktop\lol-bot-1.3.2> & C:/Users/Slavfucious/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/Users/Slavfucious/Desktop/lol-bot-1.3.2/scripts/main.py

                ──────▄▌▐▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▌
                ───▄▄██▌█ BEEP BEEP
                ▄▄▄▌▐██▌█ -15 LP DELIVERY
                ███████▌█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▌
                ▀(⊙)▀▀▀▀▀▀▀(⊙)(⊙)▀▀▀▀▀▀▀▀▀▀(⊙)

                        LoL Bot

[04 Oct 2023 12:21:49] [INFO   ] [set_game_config      ] Overwriting/creating game config
[04 Oct 2023 12:21:49] [ERROR  ] [account_loop         ] [Errno 2] No such file or directory: 'C:\\Users\\Slavfucious\\Desktop\\resources\\game.cfg'
Traceback (most recent call last):
  File "c:\Users\Slavfucious\Desktop\lol-bot-1.3.2\scripts\client.py", line 49, in account_loop
    self.launcher.launch_league(account.get_username(), account.get_password())
  File "c:\Users\Slavfucious\Desktop\lol-bot-1.3.2\scripts\launcher.py", line 34, in launch_league
    self.set_game_config()
  File "c:\Users\Slavfucious\Desktop\lol-bot-1.3.2\scripts\launcher.py", line 43, in set_game_config
    shutil.copyfile(LOCAL_GAME_CONFIG_PATH, LEAGUE_GAME_CONFIG_PATH)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Slavfucious\\Desktop\\resources\\game.cfg'
[04 Oct 2023 12:21:49] [ERROR  ] [account_loop         ] None
PS C:\Users\Slavfucious\Desktop\lol-bot-1.3.2>

**Comment by iholston** [comment]
You must have removed the game.cfg file from the resources folder

**Comment by Slavfucious** [comment]
no i have not i redownloaded the zip like 4 times no help

**Comment by Slavfucious** [comment]
'C:\Users\Slavfucious\Desktop\resources\game.cfg'
it skips the folder that there is everything, any thoughs ?

**Comment by iholston** [comment]
just copy the resources folder on to your desktop and it should work fine

**Comment by Slavfucious** [comment]
nope tried that too same error

**Comment by iholston** [comment]
Yea it's just some type of pathing error, the bot can't find the game.cfg file. Not sure what more to say about it
